// English bank — part 1: Parts of speech, sentence structure, complements
export default [
{s:'Std 5–7',t:'Nouns',l:'Easy',q:'Which word is a common noun?',o:['teacher','Botswana','Neo','Monday'],a:0,e:'Common nouns name general things; proper nouns name specific ones.'},
{s:'Std 5–7',t:'Nouns',l:'Easy',q:'What is the plural of "child"?',o:['childs','children','childes','childrens'],a:1,e:'"Child" is irregular — the plural is "children".'},
{s:'Std 5–7',t:'Nouns',l:'Easy',q:'What is the plural of "knife"?',o:['knifes','knifves','knives','knife'],a:2,e:'Nouns ending in -fe often change to -ves.'},
{s:'Std 5–7',t:'Nouns',l:'Easy',q:'Which is a proper noun?',o:['city','river','school','Gaborone'],a:3,e:'Proper nouns name particular people or places and take a capital letter.'},
{s:'Std 5–7',t:'Nouns',l:'Medium',q:'A collective noun for a group of cattle is a…',o:['herd','flock','swarm','pack'],a:0,e:'Herd of cattle, flock of birds, swarm of bees, pack of dogs.'},
{s:'Std 5–7',t:'Nouns',l:'Medium',q:'Which is an abstract noun?',o:['table','honesty','dog','river'],a:1,e:'Abstract nouns name ideas and feelings you cannot touch.'},
{s:'Std 5–7',t:'Nouns',l:'Medium',q:'What is the plural of "mouse"?',o:['mouses','mices','mice','mouse'],a:2,e:'Another irregular plural.'},
{s:'Std 5–7',t:'Nouns',l:'Medium',q:'Which noun is uncountable?',o:['book','chair','pen','water'],a:3,e:'You cannot say "two waters" — it is measured, not counted.'},
{s:'Std 5–7',t:'Nouns',l:'Medium',q:'The possessive form of "the boys" (plural) is…',o:['the boys\' books','the boy\'s books','the boys books','the boys\'s books'],a:0,e:'Plural nouns ending in -s take just an apostrophe.'},
{s:'Std 5–7',t:'Nouns',l:'Hard',q:'What is the plural of "sheep"?',o:['sheeps','sheep','sheepes','sheepen'],a:1,e:'Some nouns have the same singular and plural form.'},
{s:'Std 5–7',t:'Nouns',l:'Hard',q:'A collective noun for a group of bees is a…',o:['herd','pride','swarm','school'],a:2,e:'Bees swarm; lions form a pride; fish form a school.'},
{s:'Std 5–7',t:'Nouns',l:'Hard',q:'Which sentence uses the possessive correctly?',o:['This is Neos pencil.','This is Neos\' pencil.','This is Neo pencil.','This is Neo\'s pencil.'],a:3,e:'A singular name takes apostrophe + s.'},

{s:'Std 5–7',t:'Pronouns',l:'Easy',q:'Which word is a pronoun?',o:['she','runs','quickly','red'],a:0,e:'Pronouns replace nouns.'},
{s:'Std 5–7',t:'Pronouns',l:'Easy',q:'Choose the correct pronoun: "Neo and ___ went to the shop."',o:['me','I','myself','mine'],a:1,e:'"I" is the subject form. Test it: "I went to the shop."'},
{s:'Std 5–7',t:'Pronouns',l:'Medium',q:'Which is a possessive pronoun?',o:['they','them','theirs','themselves'],a:2,e:'Possessive pronouns show ownership: mine, yours, hers, theirs.'},
{s:'Std 5–7',t:'Pronouns',l:'Medium',q:'Complete: "The teacher gave the books to Thabo and ___."',o:['I','myself','mine','me'],a:3,e:'After a preposition use the object form "me".'},
{s:'Std 5–7',t:'Pronouns',l:'Medium',q:'Which is a reflexive pronoun?',o:['himself','him','his','he'],a:0,e:'Reflexive pronouns end in -self or -selves.'},
{s:'Std 5–7',t:'Pronouns',l:'Medium',q:'Choose the correct relative pronoun: "The girl ___ won the prize is my sister."',o:['which','who','what','whose'],a:1,e:'"Who" refers to people.'},
{s:'Std 5–7',t:'Pronouns',l:'Hard',q:'Choose the correct form: "It was ___ who called."',o:['him','his','he','himself'],a:2,e:'After the verb "to be" the subject form is correct in formal English.'},
{s:'Std 5–7',t:'Pronouns',l:'Hard',q:'Which sentence is correct?',o:['Each learner must bring their books.','Each learners must bring his book.','Each learner must brings his book.','Each learner must bring his or her book.'],a:3,e:'"Each" is singular, so the pronoun should be singular.'},
{s:'Std 5–7',t:'Pronouns',l:'Medium',q:'Which pronoun refers to a thing?',o:['it','she','he','they'],a:0,e:'"It" replaces a singular non-person noun.'},

{s:'Std 5–7',t:'Verbs',l:'Easy',q:'Which word is a verb?',o:['table','jump','blue','slowly'],a:1,e:'Verbs express actions or states.'},
{s:'Std 5–7',t:'Verbs',l:'Easy',q:'Choose the correct verb: "The learners ___ writing their exams."',o:['is','was','are','be'],a:2,e:'"Learners" is plural, so it takes "are".'},
{s:'Std 5–7',t:'Verbs',l:'Easy',q:'What is the past tense of "go"?',o:['goed','gone','going','went'],a:3,e:'"Go" is irregular: go, went, gone.'},
{s:'Std 5–7',t:'Verbs',l:'Easy',q:'What is the past tense of "write"?',o:['wrote','writed','written','writing'],a:0,e:'Write, wrote, written.'},
{s:'Std 5–7',t:'Verbs',l:'Medium',q:'Choose the correct form: "She ___ to school every day."',o:['walk','walks','walking','walked yesterday'],a:1,e:'Third person singular in the present tense adds -s.'},
{s:'Std 5–7',t:'Verbs',l:'Medium',q:'Which sentence is in the present continuous tense?',o:['They played football.','They play football.','They are playing football.','They will play football.'],a:2,e:'Present continuous uses is/are + verb-ing.'},
{s:'Std 5–7',t:'Verbs',l:'Medium',q:'What is the past participle of "eat"?',o:['ate','eating','eats','eaten'],a:3,e:'Eat, ate, eaten.'},
{s:'Std 5–7',t:'Verbs',l:'Medium',q:'Which is an auxiliary (helping) verb in "She has finished"?',o:['has','she','finished','none'],a:0,e:'"Has" helps form the perfect tense.'},
{s:'Std 5–7',t:'Verbs',l:'Medium',q:'Choose the correct tense: "By next year I ___ Standard 7."',o:['completed','will have completed','complete','have completed'],a:1,e:'A future action completed before a future time uses the future perfect.'},
{s:'Std 5–7',t:'Verbs',l:'Hard',q:'Which sentence is in the passive voice?',o:['The ball broke the window.','The ball is breaking the window.','The window was broken by the ball.','Break the window.'],a:2,e:'In the passive, the subject receives the action.'},
{s:'Std 5–7',t:'Verbs',l:'Hard',q:'Change to passive: "The teacher marked the books."',o:['The books marked the teacher.','The teacher was marked.','The books are marking.','The books were marked by the teacher.'],a:3,e:'The object becomes the subject and the verb takes "were" + past participle.'},
{s:'Std 5–7',t:'Verbs',l:'Hard',q:'Which sentence uses the subjunctive correctly?',o:['If I were you, I would study.','If I was you, I would study.','If I am you, I study.','If I be you, I study.'],a:0,e:'"Were" is used for hypothetical situations.'},
{s:'Std 5–7',t:'Verbs',l:'Hard',q:'A transitive verb is one that…',o:['never takes an object','takes a direct object','has no tense','is always passive'],a:1,e:'"She kicked the ball" — "ball" is the direct object.'},

{s:'Std 5–7',t:'Adjectives',l:'Easy',q:'Which word is an adjective?',o:['beautifully','beauty','beautiful','beautify'],a:2,e:'Adjectives describe nouns.'},
{s:'Std 5–7',t:'Adjectives',l:'Easy',q:'Complete: "This paper was ___ than the last one."',o:['more easy','easyer','most easy','easier'],a:3,e:'Short adjectives add -er; "easy" drops the y.'},
{s:'Std 5–7',t:'Adjectives',l:'Medium',q:'What is the superlative of "good"?',o:['best','goodest','more good','better'],a:0,e:'Good, better, best.'},
{s:'Std 5–7',t:'Adjectives',l:'Medium',q:'What is the comparative of "beautiful"?',o:['beautifuller','more beautiful','beautifulest','most beautiful'],a:1,e:'Longer adjectives use "more" for the comparative.'},
{s:'Std 5–7',t:'Adjectives',l:'Medium',q:'In "the tall boy ran fast", the adjective is…',o:['boy','ran','tall','fast'],a:2,e:'"Tall" describes the noun "boy".'},
{s:'Std 5–7',t:'Adjectives',l:'Medium',q:'What is the superlative of "bad"?',o:['baddest','more bad','worse','worst'],a:3,e:'Bad, worse, worst.'},
{s:'Std 5–7',t:'Adjectives',l:'Hard',q:'Which sentence uses adjectives in the correct order?',o:['a beautiful old wooden table','a wooden beautiful old table','an old beautiful wooden table','a wooden old beautiful table'],a:0,e:'Opinion comes before age, which comes before material.'},
{s:'Std 5–7',t:'Adjectives',l:'Hard',q:'Which is a demonstrative adjective?',o:['quickly','those','running','very'],a:1,e:'This, that, these, those point out which one.'},

{s:'Std 5–7',t:'Adverbs',l:'Easy',q:'Which word is an adverb in "She answered carefully"?',o:['she','answered','carefully','none'],a:2,e:'It describes how she answered.'},
{s:'Std 5–7',t:'Adverbs',l:'Easy',q:'Most adverbs of manner are formed by adding…',o:['-ing','-ed','-s','-ly to an adjective'],a:3,e:'Quick becomes quickly.'},
{s:'Std 5–7',t:'Adverbs',l:'Medium',q:'Which is an adverb of frequency?',o:['often','here','very','loudly'],a:0,e:'Always, often, never and sometimes tell how often.'},
{s:'Std 5–7',t:'Adverbs',l:'Medium',q:'In "He arrived yesterday", the adverb tells us…',o:['how','when','where','why'],a:1,e:'"Yesterday" is an adverb of time.'},
{s:'Std 5–7',t:'Adverbs',l:'Medium',q:'Which sentence uses the adverb correctly?',o:['She sings good.','She sing well.','She sings well.','She singing well.'],a:2,e:'"Well" is the adverb form of "good".'},
{s:'Std 5–7',t:'Adverbs',l:'Hard',q:'In "The very tall boy", "very" modifies…',o:['the noun "boy"','a verb','nothing','the adjective "tall"'],a:3,e:'Adverbs can modify adjectives as well as verbs.'},
{s:'Std 5–7',t:'Adverbs',l:'Hard',q:'Which is an adverb of place?',o:['outside','soon','quickly','never'],a:0,e:'It tells where the action happens.'},

{s:'Std 5–7',t:'Prepositions',l:'Easy',q:'Choose the correct preposition: "The book is ___ the table."',o:['in','on','at','of'],a:1,e:'"On" shows position on a surface.'},
{s:'Std 5–7',t:'Prepositions',l:'Easy',q:'Complete: "We arrived ___ Monday."',o:['in','at','on','to'],a:2,e:'Use "on" with days of the week.'},
{s:'Std 5–7',t:'Prepositions',l:'Medium',q:'Complete: "She is good ___ mathematics."',o:['on','in','for','at'],a:3,e:'"Good at" is the fixed expression.'},
{s:'Std 5–7',t:'Prepositions',l:'Medium',q:'Complete: "He was born ___ 2014."',o:['in','on','at','from'],a:0,e:'Use "in" with years and months.'},
{s:'Std 5–7',t:'Prepositions',l:'Medium',q:'Complete: "They are waiting ___ the bus."',o:['at','for','to','on'],a:1,e:'"Wait for" something you expect.'},
{s:'Std 5–7',t:'Prepositions',l:'Medium',q:'Complete: "The cat jumped ___ the wall."',o:['under','among','over','between'],a:2,e:'"Over" shows movement above something.'},
{s:'Std 5–7',t:'Prepositions',l:'Hard',q:'Complete: "She is different ___ her sister."',o:['than','to','of','from'],a:3,e:'"Different from" is standard usage.'},
{s:'Std 5–7',t:'Prepositions',l:'Hard',q:'Complete: "He apologised ___ being late."',o:['for','of','to','with'],a:0,e:'"Apologise for" something you did.'},
{s:'Std 5–7',t:'Prepositions',l:'Hard',q:'Choose the correct sentence.',o:['Divide the sweets among the two boys.','Divide the sweets between the two boys.','Divide the sweets between the five boys.','Divide the sweets in the two boys.'],a:1,e:'Use "between" for two, "among" for more than two.'},

{s:'Std 5–7',t:'Conjunctions',l:'Easy',q:'Which word is a conjunction?',o:['quickly','table','because','beautiful'],a:2,e:'Conjunctions join words, phrases or clauses.'},
{s:'Std 5–7',t:'Conjunctions',l:'Easy',q:'Complete: "I was late ___ the bus broke down."',o:['but','or','although','because'],a:3,e:'"Because" gives a reason.'},
{s:'Std 5–7',t:'Conjunctions',l:'Medium',q:'Complete: "___ it was raining, we played outside."',o:['Although','Because','So','And'],a:0,e:'"Although" shows contrast.'},
{s:'Std 5–7',t:'Conjunctions',l:'Medium',q:'Which conjunction shows choice?',o:['and','or','because','so'],a:1,e:'"Or" presents alternatives.'},
{s:'Std 5–7',t:'Conjunctions',l:'Medium',q:'Complete: "Study hard ___ you will pass."',o:['but','or','and','although'],a:2,e:'"And" links a result to an action.'},
{s:'Std 5–7',t:'Conjunctions',l:'Hard',q:'Which is a correlative conjunction pair?',o:['because… so','and… but','if… although','neither… nor'],a:3,e:'Either…or, neither…nor, both…and work in pairs.'},
{s:'Std 5–7',t:'Conjunctions',l:'Hard',q:'Complete: "Neither Neo ___ Thabo was present."',o:['nor','or','and','but'],a:0,e:'"Neither" pairs with "nor".'},

{s:'Std 5–7',t:'Articles & Determiners',l:'Easy',q:'Choose the correct article: "___ apple a day is healthy."',o:['A','An','The','No article'],a:1,e:'Use "an" before a vowel sound.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Easy',q:'Choose the correct article: "She is ___ honest girl."',o:['a','the','an','no article'],a:2,e:'"Honest" begins with a vowel sound because the h is silent.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Medium',q:'Choose the correct article: "He plays ___ guitar."',o:['a','an','no article','the'],a:3,e:'Use "the" with musical instruments in this sense.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Medium',q:'Complete: "There are ___ learners in the class."',o:['many','much','a little','less'],a:0,e:'"Many" is used with countable nouns.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Medium',q:'Complete: "There is not ___ water in the tank."',o:['many','much','several','few'],a:1,e:'"Much" is used with uncountable nouns.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Hard',q:'Choose the correct sentence.',o:['I have less books than she has.','I have fewer water.','I have fewer books than she has.','I have less books.'],a:2,e:'"Fewer" for countable, "less" for uncountable.'},
{s:'Std 5–7',t:'Articles & Determiners',l:'Hard',q:'Choose the correct article: "He is ___ university student."',o:['an','the','no article','a'],a:3,e:'"University" begins with a "yoo" consonant sound, so "a" is used.'},

{s:'Std 5–7',t:'Subject & Predicate',l:'Easy',q:'In "The dog barked loudly", the subject is…',o:['The dog','barked','loudly','barked loudly'],a:0,e:'The subject is who or what does the action.'},
{s:'Std 5–7',t:'Subject & Predicate',l:'Easy',q:'In "The dog barked loudly", the predicate is…',o:['The dog','barked loudly','dog','loudly'],a:1,e:'The predicate tells what the subject does.'},
{s:'Std 5–7',t:'Subject & Predicate',l:'Medium',q:'Every complete sentence must have a subject and a…',o:['adjective','adverb','verb','noun only'],a:2,e:'Without a verb it is not a sentence.'},
{s:'Std 5–7',t:'Subject & Predicate',l:'Medium',q:'In "My brother and I walked home", the subject is…',o:['walked','home','I','My brother and I'],a:3,e:'This is a compound subject.'},
{s:'Std 5–7',t:'Subject & Predicate',l:'Hard',q:'Which group of words is a complete sentence?',o:['The learners wrote the test.','After the test.','Because he was late.','Running very fast.'],a:0,e:'The others are fragments with no independent clause.'},
{s:'Std 5–7',t:'Subject & Predicate',l:'Hard',q:'In "There are many birds in the tree", the real subject is…',o:['There','many birds','are','tree'],a:1,e:'"There" is an introductory word, not the subject.'},

{s:'Std 5–7',t:'Complements',l:'Easy',q:'In "She is a nurse", the words "a nurse" are the…',o:['direct object','adverb','subject complement','preposition'],a:2,e:'A subject complement follows a linking verb and describes the subject.'},
{s:'Std 5–7',t:'Complements',l:'Easy',q:'In "He kicked the ball", "the ball" is the…',o:['subject','complement','adverb','direct object'],a:3,e:'The direct object receives the action of the verb.'},
{s:'Std 5–7',t:'Complements',l:'Medium',q:'In "She gave me the book", "me" is the…',o:['indirect object','direct object','subject','adjective'],a:0,e:'The indirect object shows to whom the action was done.'},
{s:'Std 5–7',t:'Complements',l:'Medium',q:'In "The soup tastes salty", "salty" is a…',o:['direct object','subject complement','adverb','conjunction'],a:1,e:'It describes the subject after a linking verb.'},
{s:'Std 5–7',t:'Complements',l:'Medium',q:'Which verb is a linking verb?',o:['runs','jumps','seems','writes'],a:2,e:'Linking verbs join the subject to a complement: be, seem, become, appear.'},
{s:'Std 5–7',t:'Complements',l:'Hard',q:'In "They elected him captain", "captain" is the…',o:['indirect object','subject','adverb','object complement'],a:3,e:'An object complement describes the direct object.'},
{s:'Std 5–7',t:'Complements',l:'Hard',q:'Which sentence has an indirect object?',o:['She sent her mother a letter.','She sent a letter.','She is tired.','She wrote quickly.'],a:0,e:'"Her mother" receives the direct object "a letter".'},
{s:'Std 5–7',t:'Complements',l:'Hard',q:'A verb that needs no object is called…',o:['transitive','intransitive','linking','auxiliary'],a:1,e:'"He slept" — no object is needed.'},

{s:'Std 5–7',t:'Phrases & Clauses',l:'Easy',q:'A group of words with a subject and verb is a…',o:['phrase','word','clause','syllable'],a:2,e:'A phrase has no subject-verb pair.'},
{s:'Std 5–7',t:'Phrases & Clauses',l:'Medium',q:'In "The boy in the blue shirt ran", "in the blue shirt" is a…',o:['clause','sentence','verb','phrase'],a:3,e:'It has no verb, so it is a prepositional phrase.'},
{s:'Std 5–7',t:'Phrases & Clauses',l:'Medium',q:'A clause that can stand alone is called…',o:['independent (main)','dependent','subordinate','relative'],a:0,e:'It expresses a complete thought.'},
{s:'Std 5–7',t:'Phrases & Clauses',l:'Medium',q:'In "She left because she was tired", the subordinate clause is…',o:['She left','because she was tired','she','left'],a:1,e:'It cannot stand alone as a sentence.'},
{s:'Std 5–7',t:'Phrases & Clauses',l:'Hard',q:'A sentence with two independent clauses joined by "and" is…',o:['simple','complex','compound','a fragment'],a:2,e:'Compound sentences join equal clauses.'},
{s:'Std 5–7',t:'Phrases & Clauses',l:'Hard',q:'A sentence with one main clause and one subordinate clause is…',o:['simple','compound','compound-complex','complex'],a:3,e:'Complex sentences contain a dependent clause.'},

{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Easy',q:'Choose the correct verb: "The dog ___ every night."',o:['barks','bark','barking','are barking'],a:0,e:'A singular subject takes a singular verb.'},
{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Medium',q:'Choose the correct verb: "Neither of the boys ___ present."',o:['are','is','were','have'],a:1,e:'"Neither" is singular.'},
{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Medium',q:'Choose the correct verb: "The team ___ playing well."',o:['are being','were','is','have'],a:2,e:'A collective noun acting as one unit takes a singular verb.'},
{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Medium',q:'Choose the correct verb: "Everybody ___ happy."',o:['are','were','have','is'],a:3,e:'Indefinite pronouns like everybody are singular.'},
{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Hard',q:'Choose the correct verb: "The box of pencils ___ on the desk."',o:['is','are','were','have'],a:0,e:'The subject is "box", not "pencils".'},
{s:'Std 5–7',t:'Subject-Verb Agreement',l:'Hard',q:'Choose the correct verb: "Ten pula ___ enough."',o:['are','is','were','have been'],a:1,e:'An amount treated as one sum takes a singular verb.'},

{s:'Std 5–7',t:'Question Tags & Question Forms',l:'Easy',q:'Add the tag: "You are coming, ___?"',o:['isn\'t it','are you','aren\'t you','do you'],a:2,e:'A positive statement takes a negative tag.'},
{s:'Std 5–7',t:'Question Tags & Question Forms',l:'Medium',q:'Add the tag: "She doesn\'t like tea, ___?"',o:['doesn\'t she','is she','do she','does she'],a:3,e:'A negative statement takes a positive tag.'},
{s:'Std 5–7',t:'Question Tags & Question Forms',l:'Medium',q:'Which is the correct question form?',o:['Where do you live?','Where you live?','Where you do live?','Where lives you?'],a:0,e:'Questions use the auxiliary before the subject.'},
{s:'Std 5–7',t:'Question Tags & Question Forms',l:'Hard',q:'Add the tag: "Let\'s go now, ___?"',o:['will we','shall we','do we','don\'t we'],a:1,e:'"Let\'s" takes "shall we".'},
{s:'Std 5–7',t:'Question Tags & Question Forms',l:'Hard',q:'Which question asks for a reason?',o:['When were you late?','Where were you late?','Why were you late?','How late were you?'],a:2,e:'"Why" asks for a reason.'}
];
