// Moral Education bank — Botswana PSLE (Standard 5-7)
// Format: {s: standard, t: topic, l: level, q: question, o: [options], a: correct index, e: explanation}
export default [
// ── Botho and self ──
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Easy',q:'What does the Setswana concept of "botho" mean?',o:['Being a person of good character who respects others','Being wealthy','Being clever at school','Being the oldest in a family'],a:0,e:'Botho means humanity — treating others with respect, dignity and kindness. It is the value Botswana is built on.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Easy',q:'A person with good self-esteem…',o:['Thinks they are better than everyone','Knows their own worth without putting others down','Never makes mistakes','Never asks for help'],a:1,e:'Healthy self-esteem is valuing yourself while still respecting other people.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Easy',q:'Which of these is a strength you can be proud of?',o:['Having expensive shoes','Being taller than others','Being honest when it is difficult','Having many followers'],a:2,e:'Real strengths are about character, not possessions or appearance.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Medium',q:'Self-awareness means…',o:['Thinking only about yourself','Watching other people closely','Keeping secrets','Knowing your own feelings, strengths and weaknesses'],a:3,e:'Being self-aware helps you make better choices and grow.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Medium',q:'A learner who knows they lose their temper easily should…',o:['Learn ways to calm down before reacting','Accept it and never change','Blame others for annoying them','Avoid all people'],a:0,e:'Recognising a weakness is the first step to working on it.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Medium',q:'Which action best shows botho towards an elderly neighbour?',o:['Ignoring them','Greeting them properly and offering to help carry water','Laughing at how slowly they walk','Asking them for money'],a:1,e:'Botho is shown in everyday respect and practical kindness.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Hard',q:'Why is self-respect important when facing peer pressure?',o:['It makes you popular','It means you never listen to friends','It helps you say no to what you know is wrong','It stops you making friends'],a:2,e:'A learner who respects themselves is less likely to be pushed into harmful choices.'},
{s:'Std 5–7',t:'Botho and Self-Awareness',l:'Hard',q:'Someone teases you about your old uniform. The response showing greatest self-respect is to…',o:['Fight them','Steal a new uniform','Stop coming to school','Stay calm, and know your worth is not your clothes'],a:3,e:'Dignity comes from character, not from what you own.'},

// ── Family ──
{s:'Std 5–7',t:'Family Life',l:'Easy',q:'What is the main role of a family?',o:['To provide love, care and guidance','To make money','To own cattle','To win competitions'],a:0,e:'Families raise, protect and guide children.'},
{s:'Std 5–7',t:'Family Life',l:'Easy',q:'An extended family includes…',o:['Only parents and children','Grandparents, aunts, uncles and cousins as well','Only neighbours','Only school friends'],a:1,e:'In Botswana the extended family plays a large part in raising children.'},
{s:'Std 5–7',t:'Family Life',l:'Easy',q:'Which of these is a child\'s responsibility at home?',o:['Paying the rent','Choosing where the family lives','Helping with chores and respecting elders','Buying the groceries'],a:2,e:'Children contribute through helping and showing respect.'},
{s:'Std 5–7',t:'Family Life',l:'Medium',q:'How can a learner support a family going through hard times?',o:['Complain about what is missing','Demand new clothes','Stay out of the house','Help more at home and study hard'],a:3,e:'Supporting a family means easing the load and taking your own duties seriously.'},
{s:'Std 5–7',t:'Family Life',l:'Medium',q:'Why is communication important in a family?',o:['It prevents misunderstandings and builds trust','It fills the time','It helps you argue better','It is not important'],a:0,e:'Talking honestly keeps relationships healthy.'},
{s:'Std 5–7',t:'Family Life',l:'Medium',q:'A child raised by a grandmother is…',o:['Not part of a family','Part of a real and valid family','Always unhappy','Not allowed at school'],a:1,e:'Families take many forms, and all deserve respect.'},
{s:'Std 5–7',t:'Family Life',l:'Hard',q:'Parents disagree in front of a child. The healthiest thing for the child to learn is that…',o:['Adults should never disagree','Shouting is normal','Disagreements happen and can be settled with respect','Families should hide everything'],a:2,e:'Children learn how to handle conflict by watching how adults handle it.'},
{s:'Std 5–7',t:'Family Life',l:'Hard',q:'Why do families teach children values from a young age?',o:['To control them','So they can win arguments','Because school does not teach','So they can behave well without being watched'],a:3,e:'Values become a person\'s own guide for life.'},

// ── Relationships and friendship ──
{s:'Std 5–7',t:'Friendship and Relationships',l:'Easy',q:'A good friend is someone who…',o:['Encourages you to do what is right','Always agrees with you','Has the most money','Never disagrees'],a:0,e:'True friends want what is good for you, even when it is not easy to say.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Easy',q:'What is peer pressure?',o:['Pressure from teachers','Influence from people your own age to behave a certain way','School fees','Exam stress'],a:1,e:'Peer pressure can push learners towards good or harmful behaviour.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Easy',q:'If a friend asks you to steal, the right response is to…',o:['Do it so they still like you','Steal but return it later','Refuse and explain why it is wrong','Tell them to do it alone'],a:2,e:'Real friendship never requires you to do wrong.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Medium',q:'Which is an example of negative peer pressure?',o:['Friends studying with you','Friends helping you revise','Friends encouraging honesty','Friends urging you to skip school'],a:3,e:'Negative pressure leads towards harm; positive pressure builds you up.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Medium',q:'Bullying is best described as…',o:['Repeatedly hurting or frightening someone weaker','A single accident','Playing a game','Healthy competition'],a:0,e:'Bullying involves repeated harm and a difference in power.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Medium',q:'What should you do if you see a learner being bullied?',o:['Join in','Report it to a teacher and support the learner','Laugh and film it','Say nothing to anyone'],a:1,e:'Standing by silently allows bullying to continue.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Hard',q:'Why is it wrong to spread gossip about a classmate?',o:['It wastes time','It is boring','It damages their dignity and may not even be true','Teachers dislike it'],a:2,e:'Gossip harms reputation and breaks trust, which is the opposite of botho.'},
{s:'Std 5–7',t:'Friendship and Relationships',l:'Hard',q:'A friend shares something private and asks you to keep it secret. You should break that trust only if…',o:['You are curious','You are bored','Others want to know','Someone is in danger of being harmed'],a:3,e:'Safety comes before secrecy — a trusted adult must be told if someone is at risk.'},

// ── Values and honesty ──
{s:'Std 5–7',t:'Honesty and Integrity',l:'Easy',q:'Honesty means…',o:['Telling the truth even when it is difficult','Telling people what they want to hear','Never speaking','Keeping all secrets'],a:0,e:'Honesty is truthfulness in word and action.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Easy',q:'You find P50 on the school floor. The honest action is to…',o:['Keep it quietly','Hand it to a teacher','Share it with friends','Hide it and come back later'],a:1,e:'Property that is not yours should be handed in so the owner can claim it.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Easy',q:'Cheating in an exam is wrong because…',o:['It is difficult to do','Teachers get angry','It is unfair and the marks are not truly yours','It takes too long'],a:2,e:'Cheating steals an advantage and hides what you actually know.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Medium',q:'Integrity means…',o:['Being liked by everyone','Following the crowd','Never being caught','Doing what is right even when nobody is watching'],a:3,e:'Integrity is consistency between your values and your actions.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Medium',q:'A learner breaks a window by accident. Showing responsibility means…',o:['Admitting it and offering to help repair it','Blaming someone else','Running away','Saying nothing'],a:0,e:'Owning a mistake is part of being trustworthy.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Medium',q:'Why do people trust an honest person more over time?',o:['They are louder','Their words have proved reliable','They are richer','They are older'],a:1,e:'Trust is built by a record of truthfulness.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Hard',q:'Corruption harms a country because it…',o:['Makes work faster','Creates jobs','Takes resources meant for everyone and gives them to a few','Improves services'],a:2,e:'Corruption diverts public money away from schools, clinics and roads.'},
{s:'Std 5–7',t:'Honesty and Integrity',l:'Hard',q:'A shopkeeper gives you too much change. Integrity requires that you…',o:['Keep quiet about it','Spend it quickly','Tell your friends','Return the extra money'],a:3,e:'Integrity does not depend on whether the mistake was yours.'},

// ── Rights and responsibilities ──
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Easy',q:'Which is a right of every child?',o:['The right to education','The right to do whatever they want','The right to skip school','The right to break rules'],a:0,e:'Children have rights to education, health care, protection and a name.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Easy',q:'Every right comes with a…',o:['Payment','Responsibility','Reward','Punishment'],a:1,e:'A right to education carries a responsibility to attend and work.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Easy',q:'Child labour is wrong because it…',o:['Pays too little','Is tiring','Denies a child education and harms their development','Is unpopular'],a:2,e:'Children need school and protection, not adult work burdens.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Medium',q:'A learner has the right to be safe at school. This means…',o:['They can do as they please','They need not follow rules','They cannot be corrected','They should be protected from violence and abuse'],a:3,e:'Safety includes protection from bullying, violence and abuse.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Medium',q:'Who should a learner tell if an adult is hurting them?',o:['A trusted adult such as a teacher, nurse, or the police','Nobody','Only their friends','Only social media'],a:0,e:'Abuse must always be reported to someone who can act on it.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Medium',q:'Freedom of speech means you may express your views…',o:['In any way at all','While respecting others and not spreading harm','Only in agreement with others','Only in writing'],a:1,e:'Rights are exercised within respect for other people\'s dignity.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Hard',q:'Why is it wrong to discriminate against a learner living with a disability?',o:['It is against school rules only','It upsets teachers','Every person has equal dignity and equal rights','It is old-fashioned'],a:2,e:'Equal dignity is the foundation of human rights.'},
{s:'Std 5–7',t:'Rights and Responsibilities',l:'Hard',q:'A responsibility that comes with living in a community is to…',o:['Take what you need','Avoid neighbours','Ignore rules you dislike','Obey laws and care for shared property'],a:3,e:'Communities work when members accept shared duties.'},

// ── Decision making ──
{s:'Std 5–7',t:'Making Good Decisions',l:'Easy',q:'The first step in making a good decision is to…',o:['Understand the problem clearly','Ask a friend to decide','Do the easiest thing','Wait and hope'],a:0,e:'Good decisions begin with understanding what you are actually deciding.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Easy',q:'Before making an important choice you should consider…',o:['Only what feels nice now','The consequences for yourself and others','Only what friends say','Only what is fastest'],a:1,e:'Thinking about consequences is what separates a decision from an impulse.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Medium',q:'Which decision shows good long-term thinking?',o:['Copying homework','Skipping school to rest','Revising tonight instead of watching television','Spending all your money today'],a:2,e:'Good decisions weigh future benefit against present comfort.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Medium',q:'If you are unsure about a serious decision, the wisest step is to…',o:['Decide quickly and forget it','Follow whatever friends do','Do nothing','Ask a trusted adult for advice'],a:3,e:'Seeking guidance is a sign of maturity, not weakness.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Medium',q:'Assertiveness means…',o:['Saying what you need clearly and respectfully','Shouting to get your way','Staying silent always','Being rude'],a:0,e:'Assertiveness sits between being passive and being aggressive.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Hard',q:'Why do people sometimes make poor choices under pressure?',o:['They are not clever','Strong emotion makes it harder to think about consequences','They have no values','They enjoy trouble'],a:1,e:'Calming down first is a practical way to make better decisions.'},
{s:'Std 5–7',t:'Making Good Decisions',l:'Hard',q:'A learner is offered money to help someone cheat. The best decision is to…',o:['Accept quietly','Ask for more money','Refuse and report it if the pressure continues','Do it once only'],a:2,e:'Accepting makes you part of the dishonesty, whatever the price.'},

// ── Work ethics ──
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Easy',q:'What does "ipelegeng" encourage?',o:['Waiting for help','Borrowing money','Avoiding work','Self-reliance and working for yourself'],a:3,e:'Ipelegeng is one of Botswana\'s national principles — carrying your own load.'},
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Easy',q:'A good work ethic includes…',o:['Punctuality, honesty and doing a task properly','Working only when watched','Finishing fast at any cost','Doing the least possible'],a:0,e:'How you work matters as much as what you produce.'},
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Easy',q:'Why is all honest work worthy of respect?',o:['Only office work matters','Every honest job contributes to the community','Only well-paid work matters','Only farming matters'],a:1,e:'Dignity of labour means no honest work is shameful.'},
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Medium',q:'A learner who wants to be self-reliant as an adult should now…',o:['Wait until they are older','Rely on relatives','Build habits of study, saving and hard work','Avoid responsibility'],a:2,e:'Habits formed young carry into adult life.'},
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Medium',q:'Why is saving money a good habit?',o:['It impresses friends','It means you never spend','It is required by law','It prepares you for needs and opportunities later'],a:3,e:'Saving creates choices in future.'},
{s:'Std 5–7',t:'Work and Self-Reliance',l:'Hard',q:'How does volunteering benefit both the community and the volunteer?',o:['It meets a real need and builds skills and character','It pays well','It fills spare time','It avoids school'],a:0,e:'Service builds the giver as much as the receiver.'},

// ── Health choices ──
{s:'Std 5–7',t:'Healthy Choices',l:'Easy',q:'Why should young people avoid alcohol?',o:['It tastes bad','It harms the developing body and judgement','It is expensive','Adults dislike it'],a:1,e:'Alcohol damages a young person\'s growing body and brain, and impairs decisions.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Easy',q:'Smoking is harmful mainly because it damages the…',o:['Hair','Fingernails','Lungs and heart','Hearing'],a:2,e:'Tobacco smoke damages lung tissue and blood vessels.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Medium',q:'A friend offers you drugs. The safest response is to…',o:['Try a little','Take it home','Say nothing and stay','Refuse firmly and leave, then tell a trusted adult'],a:3,e:'Leaving the situation and telling an adult protects you and possibly your friend.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Medium',q:'Abstinence for a young person means…',o:['Choosing not to engage in sexual activity','Eating less','Sleeping more','Avoiding sport'],a:0,e:'Abstinence protects health, education and future plans.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Medium',q:'How should a learner treat a classmate living with HIV?',o:['Avoid them completely','With the same friendship and respect as anyone else','Tell everyone','Sit far away'],a:1,e:'HIV is not spread by ordinary contact, and stigma causes real harm.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Hard',q:'Why is stigma against people living with HIV harmful to a whole community?',o:['It is impolite only','It upsets nurses','It stops people testing and getting treatment','It costs money'],a:2,e:'Fear of judgement keeps people away from testing and care, which spreads infection.'},
{s:'Std 5–7',t:'Healthy Choices',l:'Hard',q:'A learner feels sad for many weeks and loses interest in everything. They should…',o:['Keep it hidden','Wait a year','Stop eating','Speak to a trusted adult or a nurse'],a:3,e:'Mental health matters and help is available; long-lasting sadness needs support.'},

// ── Community and citizenship ──
{s:'Std 5–7',t:'Community and Citizenship',l:'Easy',q:'A good citizen of Botswana…',o:['Obeys the law and contributes to the community','Only pays attention to their own family','Avoids all rules','Never votes'],a:0,e:'Citizenship is participation as well as obedience.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Easy',q:'Which of these is a national principle of Botswana?',o:['Competition','Botho','Wealth','Silence'],a:1,e:'The national principles are democracy, development, self-reliance, unity and botho.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Medium',q:'Littering in your village shows…',o:['Confidence','Independence','A lack of care for the community','Cleverness'],a:2,e:'Caring for shared spaces is part of citizenship.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Medium',q:'What does "kagisano" mean?',o:['Hard work','Wealth','Competition','Social harmony and peaceful living together'],a:3,e:'Kagisano describes peace and harmony within a community.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Medium',q:'At the kgotla, everyone is allowed to speak. This teaches the value of…',o:['Listening to all voices before deciding','Speaking loudest','Deciding quickly','Following the chief only'],a:0,e:'"Mmualebe o bua la gagwe" — even a poor speaker has the right to be heard.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Hard',q:'Why is tolerance of different cultures and religions important in Botswana?',o:['It is required by law','It keeps peace in a country of many communities','It pleases visitors','It avoids argument'],a:1,e:'Respect for difference is what allows a diverse nation to live in kagisano.'},
{s:'Std 5–7',t:'Community and Citizenship',l:'Hard',q:'A learner sees an older person struggling at a bus rank. The botho response is to…',o:['Watch','Walk past quickly','Offer help without being asked','Laugh'],a:2,e:'Botho shows itself in small, unprompted acts.'}
];
